name: payearn_app
description: App for PayEarn subscribers.
publish_to: 'none'
version: 1.1.12+37

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  flutter_bloc: ^6.1.1
  equatable: ^1.2.5
  dartz: ^0.9.2
  shared_preferences: ^2.0.5
  connectivity: ^3.0.3
  cloud_firestore: ^1.0.1
  firebase_core: ^1.0.1
  image_picker: ^0.7.3
  email_validator: '^1.0.5'
  image: ^2.1.19
  path_provider: ^2.0.1
  firebase_storage: ^8.0.0
  intl: ^0.16.1
  font_awesome_flutter: ^8.10.0
  progress_indicators: ^0.1.5
  cached_network_image: ^2.5.0
  timeago: ^2.0.29
  photo_view: ^0.10.3
  dropdown_search: ^0.4.8
  jiffy: ^3.0.1
  random_string: ^2.1.0
  package_info: ^0.4.3+2
  flushbar: ^1.10.4
  confetti: ^0.5.4+1
  animate_do: ^1.7.5
  appodeal_flutter: ^0.5.3
  ntp: ^1.0.8
  in_app_update: ^2.0.0

dev_dependencies:
  flutter_launcher_icons: ^0.7.4
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  
  fonts:
    - family: Signatra
      fonts:
        - asset: assets/fonts/Signatra.ttf
    - family: Manrope
      fonts:
        - asset: assets/fonts/Manrope-Regular.ttf

flutter_icons:
  image_path: 'assets/images/icon.png'
  android: true
  ios: true
